image: piperift/ue4-full:4.25.4

variables:
  plugin: SaveExtension
  engine_version: 26

stages:
  - build
  - test
  - package

cache:
  paths:
    - Build/

before_script:
  # Download Piperift's CICD scripts
  - git clone https://github.com/PipeRift/CICDScripts Lib

build:
  stage: build
  script:
    - cd Lib
    - cmd.exe /c BuildPlugin.bat

test:
  stage: test
  script:
    - cd Lib
    - py test_plugin.py
  artifacts:
    paths:
      - Test/Report.xml
    reports:
      junit: Test/Report.xml

upload:
  stage: package
  script:
    - cd Lib
    - cmd.exe /c CompressPlugin.bat
    - py upload.py
