stages:
  - compile
  - test
  - deploy

variables:
  plugin: SaveExtension
  engine_version: 23

cache:
  paths:
    - Build/

build plugin:
  stage: compile
  script:
    - cmd.exe /c E:\Piperift\GitlabRunner\Lib\BuildPlugin.bat

unit test:
  stage: test
  script:
    - py E:\Piperift\GitlabRunner\Lib\test_plugin.py

upload:
  stage: deploy
  script:
    - cmd.exe /c E:\Piperift\GitlabRunner\Lib\CompressPlugin.bat
    - py E:\Piperift\GitlabRunner\Lib\upload.py
    - cmd.exe /c E:\Piperift\GitlabRunner\Lib\Upload.bat
