stages:
  - compile
  - test
  - deploy

variables:
  plugin: SaveExtension
  engine_version: 25

cache:
  paths:
    - Build/

build plugin:
  stage: compile
  script:
    - cmd.exe /c $LIB_PATH/BuildPlugin.bat

unit test:
  stage: test
  script:
    - py $LIB_PATH/test_plugin.py

upload:
  stage: deploy
  script:
    - cmd.exe /c $LIB_PATH/CompressPlugin.bat
    - py $LIB_PATH/upload.py
